package config

const (
	AVERAGE_CEO_DELAY            = 1.0
	AVERAGE_WORKER_DELAY         = 2.0
	AVERAGE_CUSTOMER_DELAY       = 30.0
	AVERAGE_MACHINE_DELAY        = 10.0
	AVERAGE_SERVICE_WORKER_DELAY = 15.0
)

const (
	TASKLIST_SIZE  = 40
	WAREHOUSE_SIZE = 100
)

const (
	NUM_WORKERS         = 5
	NUM_CUSTOMERS       = 2
	NUM_ADD_MACHINES    = 3
	NUM_MULT_MACHINES   = 3
	NUM_SERVICE_WORKERS = 2
)

const (
	VERBOSE = 0
	SILENT  = 1
)

const BREAKDOWN_PROBABILITY = 30

const MODE = VERBOSE
